#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Hideya Reizen
# SPDX-License-Identifier: BSD-3-Clause


import sys
import math

plus = 0.0
sqrt = 0.0
root = 0.0
log = 0.0

for line in sys.stdin:
        plus += float(line)
        sqrt += float(line)**2
        root += (math.sqrt(int(line)))
        log += math.log(int(line))

blank = ""
print(plus, blank, sqrt, blank, root, blank, log)
